HDF5 reference fix
When compiling with GCC 9.3.0 and HDF 1.12.0, I got the following error
and needed to make this small change to get it to compile.

```
Grid_CreateParticleTypeGrouping.C: In member function 'long_int grid::CreateParticleTypeGrouping(hid_t, hid_t, hid_t, hid_t)':
Grid_CreateParticleTypeGrouping.C:68:35: error: cannot convert 'hdset_reg_ref_t' to 'const void*'
   68 |                      H5P_DEFAULT, reference);
      |                                   ^~~~~~~~~
      |                                   |
      |                                   hdset_reg_ref_t
```